In [2]:
import pandas as pd
pd.__version__

'1.3.4'

In [3]:
df = pd.read_csv('car_fuel_efficiency_2026.txt')
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2


In [4]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel', 'Hybrid'], dtype=object)

In [5]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [6]:
df['fuel_efficiency_mpg'].max()

41.2

In [7]:
df['horsepower'].median()

254.0

In [9]:
df['horsepower'].mode()

0    252.0
dtype: float64

In [13]:
df['horsepower'] = df['horsepower'].fillna(252.0)
df['horsepower'].median()

252.0

In [18]:
df_asia = df[df['origin']=='Asia']

In [28]:
X = df_asia[['model_year', 'vehicle_weight']].head(7).values
X

array([[1996, 4240],
       [1992, 4310],
       [1997, 4230],
       [1978, 4420],
       [2007, 3950],
       [2021, 4750],
       [2019, 4450]])

In [37]:
import numpy as np
#XTX = X.T @ X
XTX = np.matmul(X.T, X)
XTX

array([[ 28041424,  60750580],
       [ 60750580, 131950500]])

In [40]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [44]:
w = np.matmul(np.linalg.inv(XTX), X.T) * y
w

array([[ 0.67427208,  0.13904122,  0.5529994 , -0.71637186,  2.63152339,
        -2.54924935, -0.49946567],
       [-0.27509119, -0.02155228, -0.22895733,  0.35996837, -1.18162927,
         1.21328359,  0.27042587]])

In [46]:
sum(sum(w))

0.36919696904926486